In [24]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [5]:
with open("story.txt","r",encoding="utf-8") as myfile:
  mytext = myfile.read()

In [6]:
mytext

'Learning to program is hard. It\'s difficult to know where to start, but it\'s even more challenging to know what to do after you\'ve learned the basics. Jumping into a developer bootcamp for three months isn\'t enough.\n\nThe following stories from successful developers (some of them self-taught) show you what it takes to join their ranks, highlighting how the authors learned programming and landed their first job, as well as chronicling people\'s moves from novice professional developer to exceptional software engineer.\n\n\'How I became a developer\' stories\nPeople can become developers from almost any background, whether they started programming at an early age and majored in computer science (CS), or they taught themselves how to code later in life. These stories focus on how the authors went from being beginning coders to getting that first job.\n\nMy journey to becoming a web developer from scratch without a CS degree\nThis article by Sergei Garcia is packed with excellent res

In [8]:
mytokenizer = Tokenizer()
mytokenizer.fit_on_texts([mytext])
total_words = len(mytokenizer.word_index)+1

In [9]:
mytokenizer.word_index

{'to': 1,
 'the': 2,
 'and': 3,
 'a': 4,
 'in': 5,
 'that': 6,
 'of': 7,
 'how': 8,
 'from': 9,
 'is': 10,
 'programming': 11,
 'developer': 12,
 'you': 13,
 'i': 14,
 'an': 15,
 'he': 16,
 'her': 17,
 'she': 18,
 'learning': 19,
 'it': 20,
 'first': 21,
 'job': 22,
 'with': 23,
 'years': 24,
 'know': 25,
 'but': 26,
 'after': 27,
 'learned': 28,
 'stories': 29,
 'as': 30,
 'software': 31,
 'become': 32,
 'they': 33,
 'life': 34,
 'becoming': 35,
 'this': 36,
 'his': 37,
 'should': 38,
 'was': 39,
 'program': 40,
 "it's": 41,
 'more': 42,
 'what': 43,
 "you've": 44,
 'for': 45,
 "isn't": 46,
 'developers': 47,
 'some': 48,
 'self': 49,
 'taught': 50,
 'their': 51,
 'authors': 52,
 'landed': 53,
 'can': 54,
 'almost': 55,
 'at': 56,
 'cs': 57,
 'went': 58,
 'my': 59,
 'journey': 60,
 'degree': 61,
 'garcia': 62,
 'shares': 63,
 'used': 64,
 'story': 65,
 'skills': 66,
 'helped': 67,
 'ndukwe': 68,
 'time': 69,
 'when': 70,
 'college': 71,
 'build': 72,
 'account': 73,
 'important': 74,


In [10]:
my_input_sequences = []
for line in mytext.split('\n'):
    #print(line)
    token_list = mytokenizer.texts_to_sequences([line])[0]
    #print(token_list)
    for i in range(1, len(token_list)):
        my_n_gram_sequence = token_list[:i+1]
        #print(my_n_gram_sequence)
        my_input_sequences.append(my_n_gram_sequence)
        #print(input_sequences)

In [12]:
max_sequence_len = max([len(seq) for seq in my_input_sequences])
input_sequences = np.array(pad_sequences(my_input_sequences, maxlen=max_sequence_len))

In [13]:
input_sequences[1]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       19,  1, 40], dtype=int32)

In [14]:
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [18]:
X[1]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       19,  1], dtype=int32)

In [19]:
y[1]

40

In [20]:
y

array([  1,  40,  10,  82,  41,  83,   1,  25,  84,   1,  85,  26,  41,
        86,  42,  87,   1,  25,  43,   1,  88,  27,  44,  28,   2,  89,
        90,  91,   4,  12,  92,  45,  93,  94,  46,  95,  96,  29,   9,
        97,  47,  48,   7,  98,  49,  50,  99,  13,  43,  20, 100,   1,
       101,  51, 102, 103,   8,   2,  52,  28,  11,   3,  53,  51,  21,
        22,  30, 104,  30, 105, 106, 107,   9, 108, 109,  12,   1, 110,
        31, 111,  14, 113,   4, 114,  29,  54,  32,  47,   9,  55, 116,
       117, 118,  33, 119,  11,  56,  15, 120, 121,   3, 122,   5, 123,
       124,  57, 125,  33,  50, 126,   8,   1, 127, 128,   5,  34, 129,
        29, 130, 131,   8,   2,  52,  58,   9, 132, 133, 134,   1, 135,
         6,  21,  22,  60,   1,  35,   4, 136,  12,   9, 137, 138,   4,
        57,  61, 139, 140, 141,  62,  10, 142,  23, 143, 144,  45, 145,
        19,   1,  32,   4, 146, 147,  12,  16,  63,   2, 148, 149,   7,
        37,  60, 150,  23,  55, 151, 152,   6,  16,  64,  62, 15

In [21]:
y = np.array(tf.keras.utils.to_categorical(y, num_classes=total_words))

In [22]:
y[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [25]:
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_len-1))
model.add(LSTM(150))
model.add(Dense(total_words, activation='softmax'))
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 121, 100)          25000     
                                                                 
 lstm (LSTM)                 (None, 150)               150600    
                                                                 
 dense (Dense)               (None, 250)               37750     
                                                                 
Total params: 213,350
Trainable params: 213,350
Non-trainable params: 0
_________________________________________________________________
None


In [26]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=100, verbose=1)

Epoch 1/100
15/15 [==============================] - 6s 227ms/step - loss: 5.5171 - accuracy: 0.0174
Epoch 2/100
15/15 [==============================] - 4s 276ms/step - loss: 5.3869 - accuracy: 0.0434
Epoch 3/100
15/15 [==============================] - 4s 270ms/step - loss: 5.2282 - accuracy: 0.0434
Epoch 4/100
15/15 [==============================] - 3s 229ms/step - loss: 5.1574 - accuracy: 0.0434
Epoch 5/100
15/15 [==============================] - 3s 228ms/step - loss: 5.1066 - accuracy: 0.0542
Epoch 6/100
15/15 [==============================] - 5s 337ms/step - loss: 5.0399 - accuracy: 0.0542
Epoch 7/100
15/15 [==============================] - 4s 234ms/step - loss: 4.9789 - accuracy: 0.0564
Epoch 8/100
15/15 [==============================] - 3s 228ms/step - loss: 4.9035 - accuracy: 0.0542
Epoch 9/100
15/15 [==============================] - 5s 336ms/step - loss: 4.8368 - accuracy: 0.0651
Epoch 10/100
15/15 [==============================] - 3s 230ms/step - loss: 4.7477 - accura

In [31]:
input_text = "How I became a developer"
predict_next_words= 20

for _ in range(predict_next_words):
    token_list = mytokenizer.texts_to_sequences([input_text])[0]
    # print(token_list)
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in mytokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

1/1 [==============================] - 0s 32ms/step
How I became a developer from mopping floors at a tanning salon to becoming a software developer from a degree and how she made the
